import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar/page";
import Bottom from "./bottom/page";
import localFont from "next/font/local";
import {Analytics} from "@vercel/analytics/next";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const satoshi = localFont({
  src: "../public/fonts/Satoshi-Regular.otf", // Added '..' to go up to root
  variable: "--font-satoshi",
});

const sfMono = localFont({
  src: "../public/fonts/SFMonoRegular.otf", // Added '..' to go up to root
  variable: "--font-sf-mono",
});

const gambetta = localFont({
  src: "../public/fonts/Gambetta-Regular.woff2", 
  variable: "--font-gambetta",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable} ${gambetta.variable} ${sfMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
        <Bottom />
        <Analytics />
      </body>
    </html>
  );
}
